/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Act01;

import Act01.menu_alumne_eliminar;
import Act01.menu_alumne_inserir;
import Act01.menu_alumne_modificar;
import Act01.menu_alumne_calumne;
import Act01.menu_alumne_alumnes;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author KOKO
 */
public class menu_alumne extends javax.swing.JFrame {

    /**
     * Creates new form menu_alumne
     */
    public menu_alumne() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        bINSERIR = new javax.swing.JButton();
        bMODIFICAR = new javax.swing.JButton();
        bESBORRAR = new javax.swing.JButton();
        bCALUMNE = new javax.swing.JButton();
        bALUMNES = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(153, 153, 153));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("- MENU ALUMNES -");

        bINSERIR.setBackground(new java.awt.Color(153, 153, 153));
        bINSERIR.setText("INSERIR");
        bINSERIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bINSERIRActionPerformed(evt);
            }
        });

        bMODIFICAR.setBackground(new java.awt.Color(153, 153, 153));
        bMODIFICAR.setText("MODIFICAR");
        bMODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMODIFICARActionPerformed(evt);
            }
        });

        bESBORRAR.setBackground(new java.awt.Color(153, 153, 153));
        bESBORRAR.setText("ESBORRAR");
        bESBORRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bESBORRARActionPerformed(evt);
            }
        });

        bCALUMNE.setBackground(new java.awt.Color(153, 153, 153));
        bCALUMNE.setText("CONSULTA ALUMNE");
        bCALUMNE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCALUMNEActionPerformed(evt);
            }
        });

        bALUMNES.setBackground(new java.awt.Color(153, 153, 153));
        bALUMNES.setText("ALUMNES");
        bALUMNES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bALUMNESActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bESBORRAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bMODIFICAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bINSERIR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(bCALUMNE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bALUMNES, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bINSERIR)
                .addGap(18, 18, 18)
                .addComponent(bMODIFICAR)
                .addGap(18, 18, 18)
                .addComponent(bESBORRAR)
                .addGap(18, 18, 18)
                .addComponent(bCALUMNE)
                .addGap(18, 18, 18)
                .addComponent(bALUMNES)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bINSERIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bINSERIRActionPerformed
        try {
            // TODO add your handling code here:
            menu_alumne_inserir menuAlumneInserir = new menu_alumne_inserir();
            menuAlumneInserir.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(menu_alumne.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(menu_alumne.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bINSERIRActionPerformed

    private void bMODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMODIFICARActionPerformed
        try {
            // TODO add your handling code here:
            menu_alumne_modificar menuAlumneModificar = new menu_alumne_modificar();
            menuAlumneModificar.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(menu_alumne.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(menu_alumne.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bMODIFICARActionPerformed

    private void bESBORRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bESBORRARActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            menu_alumne_eliminar menuAlumneEliminar = new menu_alumne_eliminar();
            menuAlumneEliminar.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(menu_alumne.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(menu_alumne.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bESBORRARActionPerformed

    private void bCALUMNEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCALUMNEActionPerformed
        try {
            // TODO add your handling code here:
            menu_alumne_calumne menuAlumneCAlumne = new menu_alumne_calumne();
            menuAlumneCAlumne.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(menu_alumne.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(menu_alumne.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bCALUMNEActionPerformed

    private void bALUMNESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bALUMNESActionPerformed
        try {
            // TODO add your handling code here:
            menu_alumne_alumnes menuAlumneAlumnes = new menu_alumne_alumnes();
            menuAlumneAlumnes.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(menu_alumne.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(menu_alumne.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bALUMNESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_alumne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_alumne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_alumne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_alumne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_alumne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bALUMNES;
    private javax.swing.JButton bCALUMNE;
    private javax.swing.JButton bESBORRAR;
    private javax.swing.JButton bINSERIR;
    private javax.swing.JButton bMODIFICAR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
