/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Act02;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author KOKO
 */
public class menu_principal extends javax.swing.JFrame {
    Act02 connect  = new Act02();
    Connection conection;

    /**
     * Creates new form menu_principal
     */
    public menu_principal() throws SQLException, ClassNotFoundException {
        initComponents();
        this.conection = connect.conexionJDBC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        bGENERAR = new javax.swing.JButton();
        bESBORRAR = new javax.swing.JButton();
        bSORTIR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(153, 153, 153));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("- MENU -");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        bGENERAR.setBackground(new java.awt.Color(153, 153, 153));
        bGENERAR.setText("GENERA DADES");
        bGENERAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGENERARActionPerformed(evt);
            }
        });

        bESBORRAR.setBackground(new java.awt.Color(153, 153, 153));
        bESBORRAR.setText("ESBORRAR DADES");
        bESBORRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bESBORRARActionPerformed(evt);
            }
        });

        bSORTIR.setBackground(new java.awt.Color(153, 153, 153));
        bSORTIR.setText("SORTIR");
        bSORTIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSORTIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bESBORRAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bGENERAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(bSORTIR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bGENERAR)
                .addGap(18, 18, 18)
                .addComponent(bESBORRAR)
                .addGap(18, 18, 18)
                .addComponent(bSORTIR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGENERARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGENERARActionPerformed
        // TODO add your handling code here:
        try  {
            Statement comando = conection.createStatement();
            comando.executeUpdate("INSERT INTO alumnes (NOM, DNI, "
                    + "NAIXEMENT, ADRECA, SEXE, CODIPOSTAL, POBLACIO) VALUES "
                    + "('Ivan', '39955227H', '2001/01/27', 'Av. dels Països Catalans', 'M', 43206, 'Reus');");
            comando.executeUpdate("INSERT INTO alumnes (NOM, DNI, "
                    + "NAIXEMENT, ADRECA, SEXE, CODIPOSTAL, POBLACIO) VALUES "
                    + "('Elsa', '39967815L', '2006/06/14', 'Carrer de la Argentera', 'F', 43202, 'Reus');");
            comando.executeUpdate("INSERT INTO alumnes (NOM, DNI, "
                    + "NAIXEMENT, ADRECA, SEXE, CODIPOSTAL, POBLACIO) VALUES "
                    + "('Jose', '39968431P', '1969/11/20', 'Av. dels Països Catalans', 'M', 43206, 'Reus');");
            JOptionPane.showMessageDialog(null, "Dades generades correctament");
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error al generar les dades dels alumnes!!!" + e);
        }
        

    }//GEN-LAST:event_bGENERARActionPerformed

    private void bESBORRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bESBORRARActionPerformed
        // TODO add your handling code here:
        try {
            Statement comando = conection.createStatement();
            comando.executeUpdate("DELETE FROM alumnes;");
            JOptionPane.showMessageDialog(null, "Dades esborrades correctament");
        } catch (SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, "Error al borrar les dades dels alumnes!!!" + e);
        }
    }//GEN-LAST:event_bESBORRARActionPerformed

    private void bSORTIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSORTIRActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bSORTIRActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new menu_principal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(menu_principal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(menu_principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bESBORRAR;
    private javax.swing.JButton bGENERAR;
    private javax.swing.JButton bSORTIR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
